const { spawnSync, spawn } = require('child_process')
const { existsSync, writeFileSync } = require('fs')
const path = require('path')

const SESSION_ID = 'SUHAIL_21_37_04_21_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQwLFxuICAgICAgICAxNTcsXG4gICAgICAgIDczLFxuICAgICAgICAyNDgsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMTk5LFxuICAgICAgICAxOTYsXG4gICAgICAgIDE4LFxuICAgICAgICAxMjcsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMixcbiAgICAgICAgODMsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMjM5LFxuICAgICAgICAyMDEsXG4gICAgICAgIDIwMyxcbiAgICAgICAgODIsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTU4LFxuICAgICAgICAxMzQsXG4gICAgICAgIDksXG4gICAgICAgIDkzLFxuICAgICAgICAxODIsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTg3LFxuICAgICAgICAxMCxcbiAgICAgICAgODgsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMTc0LFxuICAgICAgICAyNDQsXG4gICAgICAgIDU0LFxuICAgICAgICAxMTBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTU5LFxuICAgICAgICAxNjIsXG4gICAgICAgIDQ3LFxuICAgICAgICA0MCxcbiAgICAgICAgMTgyLFxuICAgICAgICAxMjIsXG4gICAgICAgIDg4LFxuICAgICAgICAyMTEsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMzgsXG4gICAgICAgIDMsXG4gICAgICAgIDEzLFxuICAgICAgICAxODcsXG4gICAgICAgIDIxMCxcbiAgICAgICAgNjAsXG4gICAgICAgIDIzMixcbiAgICAgICAgMjE0LFxuICAgICAgICAyMjUsXG4gICAgICAgIDEwMCxcbiAgICAgICAgNTYsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMjUxLFxuICAgICAgICAxNDEsXG4gICAgICAgIDExLFxuICAgICAgICA5NSxcbiAgICAgICAgMjE2LFxuICAgICAgICAyNTEsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTcyLFxuICAgICAgICAxNTQsXG4gICAgICAgIDI1NCxcbiAgICAgICAgOTVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTkzLFxuICAgICAgICA5MixcbiAgICAgICAgMTU4LFxuICAgICAgICA4NCxcbiAgICAgICAgMjUsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMjM3LFxuICAgICAgICAxODUsXG4gICAgICAgIDE2NSxcbiAgICAgICAgNTcsXG4gICAgICAgIDUsXG4gICAgICAgIDk5LFxuICAgICAgICAxNTMsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTkxLFxuICAgICAgICA0OSxcbiAgICAgICAgMjQyLFxuICAgICAgICA2NixcbiAgICAgICAgODEsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTMxLFxuICAgICAgICAxMTcsXG4gICAgICAgIDI2LFxuICAgICAgICAyMjQsXG4gICAgICAgIDQ1LFxuICAgICAgICAyMTYsXG4gICAgICAgIDExNixcbiAgICAgICAgNjksXG4gICAgICAgIDMxLFxuICAgICAgICAyNDksXG4gICAgICAgIDExM1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA3NyxcbiAgICAgICAgMjQ1LFxuICAgICAgICA1MixcbiAgICAgICAgMTUsXG4gICAgICAgIDg3LFxuICAgICAgICAyMDQsXG4gICAgICAgIDMwLFxuICAgICAgICA0NCxcbiAgICAgICAgMTQzLFxuICAgICAgICA4MCxcbiAgICAgICAgNjcsXG4gICAgICAgIDExLFxuICAgICAgICAyMzEsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTAyLFxuICAgICAgICAxMjYsXG4gICAgICAgIDE0MixcbiAgICAgICAgMjEzLFxuICAgICAgICAyMTksXG4gICAgICAgIDcwLFxuICAgICAgICAyNDIsXG4gICAgICAgIDk3LFxuICAgICAgICAxNzEsXG4gICAgICAgIDI1MCxcbiAgICAgICAgODQsXG4gICAgICAgIDQ5LFxuICAgICAgICAyMjEsXG4gICAgICAgIDIxLFxuICAgICAgICA1LFxuICAgICAgICAxMjYsXG4gICAgICAgIDMwLFxuICAgICAgICA5NlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNjQsXG4gICAgICAgIDI0OSxcbiAgICAgICAgNzgsXG4gICAgICAgIDEyNyxcbiAgICAgICAgMTIzLFxuICAgICAgICAyOCxcbiAgICAgICAgMjQ0LFxuICAgICAgICA3OSxcbiAgICAgICAgMTgyLFxuICAgICAgICAxMDQsXG4gICAgICAgIDE5MixcbiAgICAgICAgMjE2LFxuICAgICAgICA1NCxcbiAgICAgICAgMjE4LFxuICAgICAgICA4OCxcbiAgICAgICAgMTIxLFxuICAgICAgICAxNzUsXG4gICAgICAgIDIxLFxuICAgICAgICAxNzIsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMjE2LFxuICAgICAgICAyMTksXG4gICAgICAgIDE4MSxcbiAgICAgICAgMzYsXG4gICAgICAgIDE0NCxcbiAgICAgICAgODYsXG4gICAgICAgIDExLFxuICAgICAgICA1MSxcbiAgICAgICAgMjI4LFxuICAgICAgICA4NCxcbiAgICAgICAgMTcwLFxuICAgICAgICA5MFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNDEsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTE4LFxuICAgICAgICAxMzMsXG4gICAgICAgIDIyMCxcbiAgICAgICAgODgsXG4gICAgICAgIDksXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTY2LFxuICAgICAgICAyMjgsXG4gICAgICAgIDQ3LFxuICAgICAgICAyNDQsXG4gICAgICAgIDE4LFxuICAgICAgICA0LFxuICAgICAgICAyNyxcbiAgICAgICAgMyxcbiAgICAgICAgMzAsXG4gICAgICAgIDIwNixcbiAgICAgICAgOTQsXG4gICAgICAgIDYxLFxuICAgICAgICAyMDAsXG4gICAgICAgIDYwLFxuICAgICAgICAxMDAsXG4gICAgICAgIDI1MixcbiAgICAgICAgMTAzLFxuICAgICAgICAyMzksXG4gICAgICAgIDgyLFxuICAgICAgICAxMDIsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjMwLFxuICAgICAgICAxNDgsXG4gICAgICAgIDRcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgMjUwLFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDIsXG4gICAgICAgICAgMTgsXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDEyMyxcbiAgICAgICAgICAyMzAsXG4gICAgICAgICAgNTAsXG4gICAgICAgICAgMTYzLFxuICAgICAgICAgIDIxMCxcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICAyLFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAyMjQsXG4gICAgICAgICAgMjksXG4gICAgICAgICAgMjIxLFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgMjUyLFxuICAgICAgICAgIDksXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMjcsXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDk3XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDYyLFxuICAgICAgICAgIDEsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDIsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDI0NixcbiAgICAgICAgICA2OCxcbiAgICAgICAgICA2NixcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAxNzUsXG4gICAgICAgICAgMTAxLFxuICAgICAgICAgIDI1MSxcbiAgICAgICAgICA2NCxcbiAgICAgICAgICA4NixcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgMyxcbiAgICAgICAgICA5MyxcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgMTc0LFxuICAgICAgICAgIDIyOCxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDU1LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAxNjQsXG4gICAgICAgICAgMzlcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDksXG4gICAgICAgIDIxNixcbiAgICAgICAgODQsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTA2LFxuICAgICAgICAxNzYsXG4gICAgICAgIDE5NyxcbiAgICAgICAgNjIsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMTU1LFxuICAgICAgICAxMTEsXG4gICAgICAgIDc5LFxuICAgICAgICAyMzYsXG4gICAgICAgIDIxOCxcbiAgICAgICAgNjcsXG4gICAgICAgIDI0MixcbiAgICAgICAgMjQxLFxuICAgICAgICA4MSxcbiAgICAgICAgMTc0LFxuICAgICAgICA3MixcbiAgICAgICAgMTA4LFxuICAgICAgICAyMTQsXG4gICAgICAgIDE3MixcbiAgICAgICAgMjEyLFxuICAgICAgICAyMjksXG4gICAgICAgIDE0MSxcbiAgICAgICAgNjgsXG4gICAgICAgIDM3LFxuICAgICAgICAxNDMsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMjQwLFxuICAgICAgICAxMjUsXG4gICAgICAgIDE2NCxcbiAgICAgICAgNzgsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTU1LFxuICAgICAgICAyMjIsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTM2LFxuICAgICAgICAyMTksXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTAyLFxuICAgICAgICA4NCxcbiAgICAgICAgNjksXG4gICAgICAgIDgwLFxuICAgICAgICA5NCxcbiAgICAgICAgMTM3LFxuICAgICAgICAxNDUsXG4gICAgICAgIDIzNyxcbiAgICAgICAgNCxcbiAgICAgICAgMjEwLFxuICAgICAgICAyMTcsXG4gICAgICAgIDYyLFxuICAgICAgICAxNzYsXG4gICAgICAgIDEsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMjI2LFxuICAgICAgICA0MSxcbiAgICAgICAgNzMsXG4gICAgICAgIDgwLFxuICAgICAgICAxMSxcbiAgICAgICAgNjcsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMTBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDE2OCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCIraXdpbFZEekR1a2RrbjAwTWJhZXVVSlI1R2RhaVdmSUZBVzNOb3J6K0RnPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjI1NDcwMjM5MTkzNEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiQzc4MzY4MTFBMDg1RDFDOTk4MkI5MTk3OEU0ODhGQzdcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzQ1MjcxNDU5XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIk1XWnpvOXRiUTdxN0VVejdUSkhXbHdcIixcbiAgXCJwaG9uZUlkXCI6IFwiZTNkZGNkZWYtZjhkOS00ZTc5LTkyNTktZjNiYjI3YTFhMmE0XCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE1MyxcbiAgICAgIDU4LFxuICAgICAgMjQ2LFxuICAgICAgMTg4LFxuICAgICAgMTQ0LFxuICAgICAgMTM2LFxuICAgICAgMjQ1LFxuICAgICAgMTUxLFxuICAgICAgMTM5LFxuICAgICAgMTYxLFxuICAgICAgOTgsXG4gICAgICAyMzQsXG4gICAgICAxNDMsXG4gICAgICAxMzYsXG4gICAgICAyMTcsXG4gICAgICAyMTMsXG4gICAgICAxNjMsXG4gICAgICAyMjQsXG4gICAgICAyMDksXG4gICAgICAxOThcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjEzLFxuICAgICAgNDksXG4gICAgICA3MSxcbiAgICAgIDY2LFxuICAgICAgNzAsXG4gICAgICAxMDUsXG4gICAgICAxNDIsXG4gICAgICA2LFxuICAgICAgMjA4LFxuICAgICAgMTg5LFxuICAgICAgMTkwLFxuICAgICAgMjM0LFxuICAgICAgMjksXG4gICAgICAxMjcsXG4gICAgICAxNjksXG4gICAgICAxNjAsXG4gICAgICAxOCxcbiAgICAgIDI4LFxuICAgICAgMTM4LFxuICAgICAgMTM1XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIlA4SExXRUdBXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyNTQ3MDIzOTE5MzQ6NzFAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjEwNTQ5NzY4NDM4NTk4NTo3MUBsaWRcIixcbiAgICBcIm5hbWVcIjogXCJUZWNoaWVUYW1lclwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ015bnRwa0ZFSjcxbXNBR0dBY2dBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiMHlPR1BwRE43MStDUFVrOVhHSmhGL0Z6dmlNcityUUs4WWVFSmMyRndqbz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCIzNmxYcm45ZlFHYk1JUWNTdWM0WW9ZbFpmYVhpVlliL3ZwR20xNnJjbmhybnNOWmNjdWQrV3ltLzlqNm83WUUwQ1hBaGpPbkNoOVRjRTRCK1ljUjhDUT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJVL3dzSFYxSk5uc0gvSTBUSVVLOHVHRjVWQ3luMy9XV3NEeEhMQ0wxTHJCc2VkMzlkaUo1MkJQdTNkeHpBdTNOc3lyMFZCNlpFREE5WFkya1EzbEVEZz09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyNTQ3MDIzOTE5MzQ6NzFAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMzUsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDYyLFxuICAgICAgICAgIDE0NCxcbiAgICAgICAgICAyMDUsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICA3MyxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICA5MixcbiAgICAgICAgICA5OCxcbiAgICAgICAgICA5NyxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAzNSxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgMTgwLFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDI0MSxcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDIwNSxcbiAgICAgICAgICAxMzMsXG4gICAgICAgICAgMTk0LFxuICAgICAgICAgIDU4XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3NDUyNzE0NTgsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFJRjVcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUlGNS5qc29uIjogIntcImtleURhdGFcIjpcInNJUmk1dXFGbmJ2WWlHeEZ0U3VQcDlIajBaV25saEZaRmpyeGZ2NVlXYWM9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTM5NTQ5NTg4MyxcImN1cnJlbnRJbmRleFwiOjE4LFwiZGV2aWNlSW5kZXhlc1wiOlsxNiwwLDE4XX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iCn0=' // Edit this line only, don't remove ' <- this symbol

let nodeRestartCount = 0
const maxNodeRestarts = 5
const restartWindow = 30000 // 30 seconds
let lastRestartTime = Date.now()

function startNode() {
  const child = spawn('node', ['index.js'], { cwd: 'levanter', stdio: 'inherit' })

  child.on('exit', (code) => {
    if (code !== 0) {
      const currentTime = Date.now()
      if (currentTime - lastRestartTime > restartWindow) {
        nodeRestartCount = 0
      }
      lastRestartTime = currentTime
      nodeRestartCount++

      if (nodeRestartCount > maxNodeRestarts) {
        console.error('Node.js process is restarting continuously. Stopping retries...')
        return
      }
      console.log(
        `Node.js process exited with code ${code}. Restarting... (Attempt ${nodeRestartCount})`
      )
      startNode()
    }
  })
}

function startPm2() {
  const pm2 = spawn('yarn', ['pm2', 'start', 'index.js', '--name', 'levanter', '--attach'], {
    cwd: 'levanter',
    stdio: ['pipe', 'pipe', 'pipe'],
  })

  let restartCount = 0
  const maxRestarts = 5 // Adjust this value as needed

  pm2.on('exit', (code) => {
    if (code !== 0) {
      // console.log('yarn pm2 failed to start, falling back to node...')
      startNode()
    }
  })

  pm2.on('error', (error) => {
    console.error(`yarn pm2 error: ${error.message}`)
    startNode()
  })

  // Check for infinite restarts
  if (pm2.stderr) {
    pm2.stderr.on('data', (data) => {
      const output = data.toString()
      if (output.includes('restart')) {
        restartCount++
        if (restartCount > maxRestarts) {
          // console.log('yarn pm2 is restarting indefinitely, stopping yarn pm2 and starting node...')
          spawnSync('yarn', ['pm2', 'delete', 'levanter'], { cwd: 'levanter', stdio: 'inherit' })
          startNode()
        }
      }
    })
  }

  if (pm2.stdout) {
    pm2.stdout.on('data', (data) => {
      const output = data.toString()
      console.log(output)
      if (output.includes('Connecting')) {
        // console.log('Application is online.')
        restartCount = 0
      }
    })
  }
}

function installDependencies() {
  // console.log('Installing dependencies...')
  const installResult = spawnSync(
    'yarn',
    ['install', '--force', '--non-interactive', '--network-concurrency', '3'],
    {
      cwd: 'levanter',
      stdio: 'inherit',
      env: { ...process.env, CI: 'true' }, // Ensure non-interactive environment
    }
  )

  if (installResult.error || installResult.status !== 0) {
    console.error(
      `Failed to install dependencies: ${
        installResult.error ? installResult.error.message : 'Unknown error'
      }`
    )
    process.exit(1) // Exit the process if installation fails
  }
}

function checkDependencies() {
  if (!existsSync(path.resolve('levanter/package.json'))) {
    console.error('package.json not found!')
    process.exit(1)
  }

  const result = spawnSync('yarn', ['check', '--verify-tree'], {
    cwd: 'levanter',
    stdio: 'inherit',
  })

  // Check the exit code to determine if there was an error
  if (result.status !== 0) {
    console.log('Some dependencies are missing or incorrectly installed.')
    installDependencies()
  } else {
    // console.log('All dependencies are installed properly.')
  }
}

function cloneRepository() {
  // console.log('Cloning the repository...')
  const cloneResult = spawnSync(
    'git',
    ['clone', 'https://github.com/lyfe00011/levanter.git', 'levanter'],
    {
      stdio: 'inherit',
    }
  )

  if (cloneResult.error) {
    throw new Error(`Failed to clone the repository: ${cloneResult.error.message}`)
  }

  const configPath = 'levanter/config.env'
  try {
    // console.log('Writing to config.env...')
    writeFileSync(configPath, `VPS=true\nSESSION_ID=${SESSION_ID}`)
  } catch (err) {
    throw new Error(`Failed to write to config.env: ${err.message}`)
  }

  installDependencies()
}

if (!existsSync('levanter')) {
  cloneRepository()
  checkDependencies()
} else {
  checkDependencies()
}

startPm2()
